services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - redis
